---

# Variable configuration.
- name: Load distribution specific variables
  ansible.builtin.import_tasks: variables.yml

- name: Setup RHEL specific tasks
  ansible.builtin.import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Setup Debian specific tasks
  ansible.builtin.import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure service is installed
  ansible.builtin.command:
    cmd: graylog-sidecar -service install
    creates: /etc/systemd/system/graylog-sidecar.service
  notify: restart graylog

- name: Setup /etc/graylog/sidecar/sidecar.yml
  ansible.builtin.template:
    src: "{{ sidecar_config_template }}"
    dest: /etc/graylog/sidecar/sidecar.yml
    mode: 0640
    owner: root
    group: root
  notify: restart graylog

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup collector configuration
  ansible.builtin.include_tasks: setup-collector-configuration.yml
  args:
    apply:
      delegate_to: localhost
  loop: "{{ sidecar_collector_config | default([]) }}"
  loop_control:
    label: "{{ item.collector }} - {{ item.configuration }}"
