---

# Variable configuration.
- include_tasks: variables.yml

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: setup | install the service
  command:
    cmd: graylog-sidecar -service install
    creates: /etc/systemd/system/graylog-sidecar.service
  notify: restart graylog

- name: setup | deploy /etc/graylog/sidecar/sidecar.yml
  template:
    src: "{{ sidecar_config_template }}"
    dest: /etc/graylog/sidecar/sidecar.yml
    mode: 0640
    owner: root
    group: root
  notify: restart graylog

- name: meta | Flush handlers
  meta: flush_handlers

- name: setup | collector configuration
  include_tasks: setup-collector-configuration.yml
  loop: "{{ sidecar_collector_config | default([]) }}"
  loop_control:
    label:
      - "{{ item.collector }}"
      - "{{ item.configuration }}"